package main

import (
	"encoding/xml"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gorilla/mux"
)

type Rss struct {
	XMLName xml.Name `xml:"rss"`
	Version string   `xml:"version,attr"`
	Channel Channel  `xml:"channel"`
}

type Channel struct {
	Title       string    `xml:"title"`
	Link        string    `xml:"link"`
	Description string    `xml:"description"`
	Language    string    `xml:"language"`
	TTL         int       `xml:"ttl"`
	Image       Image     `xml:"image"`
	Items       []Item    `xml:"item"`
}

type Image struct {
	URL    string `xml:"url"`
	Title  string `xml:"title"`
	Link   string `xml:"link"`
	Width  int    `xml:"width"`
	Height int    `xml:"height"`
}

type Item struct {
	Title       string    `xml:"title"`
	Creator     string    `xml:"dc:creator"`
	Description string    `xml:"description"`
	PubDate     string    `xml:"pubDate"`
	GUID        string    `xml:"guid"`
	Link        string    `xml:"link"`
}

func renderRssTweet(tweet Tweet, cfg Config) string {
	var result strings.Builder
	result.WriteString(fmt.Sprintf("<p>%s</p>", strings.ReplaceAll(tweet.Text, "\n", "<br>\n")))

	if len(tweet.Photos) > 0 {
		for _, photo := range tweet.Photos {
			result.WriteString(fmt.Sprintf("<img src=\"%s\" style=\"max-width:250px;\" />", getPicUrl(photo)))
		}
	} else if len(tweet.Videos) > 0 {
		for _, video := range tweet.Videos {
			result.WriteString(fmt.Sprintf("<img src=\"%s\" style=\"max-width:250px;\" />", getPicUrl(video.Thumb)))
		}
	}

	return result.String()
}

func renderRssTweets(tweets []Tweet, cfg Config) []Item {
	var items []Item
	for _, tweet := range tweets {
		items = append(items, Item{
			Title:       tweet.Text,
			Creator:     fmt.Sprintf("@%s", tweet.User.Username),
			Description: renderRssTweet(tweet, cfg),
			PubDate:     tweet.Time.Format(time.RFC1123Z),
			GUID:        fmt.Sprintf("%s/%s", cfg.Hostname, tweet.ID),
			Link:        fmt.Sprintf("%s/%s", cfg.Hostname, tweet.ID),
		})
	}
	return items
}

func renderTimelineRss(profile Profile, cfg Config) Rss {
	return Rss{
		Version: "2.0",
		Channel: Channel{
			Title:       fmt.Sprintf("%s / @%s", profile.User.Fullname, profile.User.Username),
			Link:        fmt.Sprintf("%s/%s", cfg.Hostname, profile.User.Username),
			Description: fmt.Sprintf("Twitter feed for: @%s. Generated by %s", profile.User.Username, cfg.Hostname),
			Language:    "en-us",
			TTL:         40,
			Image: Image{
				URL:    getPicUrl(profile.User.UserPic),
				Title:  profile.User.Fullname,
				Link:   fmt.Sprintf("%s/%s", cfg.Hostname, profile.User.Username),
				Width:  128,
				Height: 128,
			},
			Items: renderRssTweets(profile.Tweets, cfg),
		},
	}
}

func createRssRouter(r *mux.Router, cfg Config) {
	r.HandleFunc("/search/rss", func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query().Get("q")
		if len(query) > 200 {
			http.Error(w, "Search input too long.", http.StatusBadRequest)
			return
		}

		tweets, err := fetchTweets(query)
		if err != nil {
			http.Error(w, "Failed to fetch tweets", http.StatusInternalServerError)
			return
		}

		rss := renderTimelineRss(Profile{Tweets: tweets}, cfg)
		w.Header().Set("Content-Type", "application/rss+xml; charset=utf-8")
		xml.NewEncoder(w).Encode(rss)
	}).Methods("GET")

	r.HandleFunc("/@{name}/rss", func(w http.ResponseWriter, r *http.Request) {
		name := mux.Vars(r)["name"]
		user, err := fetchUser(name)
		if err != nil {
			http.Error(w, "User not found", http.StatusNotFound)
			return
		}

		tweets, err := fetchTweets(user.ID)
		if err != nil {
			http.Error(w, "Failed to fetch tweets", http.StatusInternalServerError)
			return
		}

		rss := renderTimelineRss(Profile{User: user, Tweets: tweets}, cfg)
		w.Header().Set("Content-Type", "application/rss+xml; charset=utf-8")
		xml.NewEncoder(w).Encode(rss)
	}).Methods("GET")

	r.HandleFunc("/@{name}/{tab}/rss", func(w http.ResponseWriter, r *http.Request) {
		name := mux.Vars(r)["name"]
		tab := mux.Vars(r)["tab"]
		if tab != "with_replies" && tab != "media" && tab != "search" {
			http.Error(w, "Invalid tab", http.StatusBadRequest)
			return
		}

		user, err := fetchUser(name)
		if err != nil {
			http.Error(w, "User not found", http.StatusNotFound)
			return
		}

		var tweets []Tweet
		switch tab {
		case "with_replies":
			tweets, err = fetchTweetsWithReplies(user.ID)
		case "media":
			tweets, err = fetchMediaTweets(user.ID)
		case "search":
			query := r.URL.Query().Get("q")
			tweets, err = fetchTweets(query)
		}

		if err != nil {
			http.Error(w, "Failed to fetch tweets", http.StatusInternalServerError)
			return
		}

		rss := renderTimelineRss(Profile{User: user, Tweets: tweets}, cfg)
		w.Header().Set("Content-Type", "application/rss+xml; charset=utf-8")
		xml.NewEncoder(w).Encode(rss)
	}).Methods("GET")

	r.HandleFunc("/@{name}/lists/{slug}/rss", func(w http.ResponseWriter, r *http.Request) {
		name := mux.Vars(r)["name"]
		slug := mux.Vars(r)["slug"]

		list, err := fetchList(name, slug)
		if err != nil {
			http.Error(w, "List not found", http.StatusNotFound)
			return
		}

		tweets, err := fetchListTweets(list.ID)
		if err != nil {
			http.Error(w, "Failed to fetch tweets", http.StatusInternalServerError)
			return
		}

		rss := renderTimelineRss(Profile{User: list.User, Tweets: tweets}, cfg)
		w.Header().Set("Content-Type", "application/rss+xml; charset=utf-8")
		xml.NewEncoder(w).Encode(rss)
	}).Methods("GET")
}
