package main

import (
	"encoding/xml"
	"fmt"
	"strings"
	"time"
)

type Rss struct {
	XMLName xml.Name `xml:"rss"`
	Version string   `xml:"version,attr"`
	Channel Channel  `xml:"channel"`
}

type Channel struct {
	Title       string    `xml:"title"`
	Link        string    `xml:"link"`
	Description string    `xml:"description"`
	Language    string    `xml:"language"`
	TTL         int       `xml:"ttl"`
	Image       Image     `xml:"image"`
	Items       []Item    `xml:"item"`
}

type Image struct {
	URL    string `xml:"url"`
	Title  string `xml:"title"`
	Link   string `xml:"link"`
	Width  int    `xml:"width"`
	Height int    `xml:"height"`
}

type Item struct {
	Title       string    `xml:"title"`
	Creator     string    `xml:"dc:creator"`
	Description string    `xml:"description"`
	PubDate     string    `xml:"pubDate"`
	GUID        string    `xml:"guid"`
	Link        string    `xml:"link"`
}

func renderRssTweet(tweet Tweet, cfg Config) string {
	var result strings.Builder
	result.WriteString(fmt.Sprintf("<p>%s</p>", strings.ReplaceAll(tweet.Text, "\n", "<br>\n")))

	if len(tweet.Photos) > 0 {
		for _, photo := range tweet.Photos {
			result.WriteString(fmt.Sprintf("<img src=\"%s\" style=\"max-width:250px;\" />", getPicUrl(photo)))
		}
	} else if len(tweet.Videos) > 0 {
		for _, video := range tweet.Videos {
			result.WriteString(fmt.Sprintf("<img src=\"%s\" style=\"max-width:250px;\" />", getPicUrl(video.Thumb)))
		}
	}

	return result.String()
}

func renderRssTweets(tweets []Tweet, cfg Config) []Item {
	var items []Item
	for _, tweet := range tweets {
		items = append(items, Item{
			Title:       tweet.Text,
			Creator:     fmt.Sprintf("@%s", tweet.User.Username),
			Description: renderRssTweet(tweet, cfg),
			PubDate:     tweet.Time.Format(time.RFC1123Z),
			GUID:        fmt.Sprintf("%s/%s", cfg.Hostname, tweet.ID),
			Link:        fmt.Sprintf("%s/%s", cfg.Hostname, tweet.ID),
		})
	}
	return items
}

func renderTimelineRss(profile Profile, cfg Config) Rss {
	return Rss{
		Version: "2.0",
		Channel: Channel{
			Title:       fmt.Sprintf("%s / @%s", profile.User.Fullname, profile.User.Username),
			Link:        fmt.Sprintf("%s/%s", cfg.Hostname, profile.User.Username),
			Description: fmt.Sprintf("Twitter feed for: @%s. Generated by %s", profile.User.Username, cfg.Hostname),
			Language:    "en-us",
			TTL:         40,
			Image: Image{
				URL:    getPicUrl(profile.User.UserPic),
				Title:  profile.User.Fullname,
				Link:   fmt.Sprintf("%s/%s", cfg.Hostname, profile.User.Username),
				Width:  128,
				Height: 128,
			},
			Items: renderRssTweets(profile.Tweets, cfg),
		},
	}
}
